openshift:
  # -- enables using arbitrary uid for argo repo server
  enabled: false
global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.


configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    tls: true