apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecs-common-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/lnf-da-control/ecs-k8s-backend.git'
    path: .
    targetRevision: HEAD
    helm:
      parameters:
        - name: namespace
          value: backend
        ## other values from values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
