namespace: backend
domain: "k8sda.lnf.infn.it"

# Kafka configuration with external LoadBalancer access
kafka:
  replicaCount: 3
  targetRevision: '30.1.6'  # Using older version due to Bitnami registry changes
  
  # CRITICAL: Must override image registry (Bitnami removed docker.io/bitnami Aug 2025)
  # Replace with your own mirrored registry
  image:
    registry: your-registry.example.com
    repository: bitnami/kafka
    tag: 3.8.0-debian-12-r5
  
  externalAccess:
    enabled: true
    controller:
      service:
        type: LoadBalancer
        # One LoadBalancer IP per replica (3 IPs for 3 replicas)
        loadBalancerIPs:
          - 10.10.6.250
          - 10.10.6.251
          - 10.10.6.252
        ports:
          external: 9092
  
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT
