apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epik8s-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/infn-epics/epik8s-backend.git'
    path: .
    targetRevision: HEAD
    helm:
      values: |
          namespace: backend
          domain: "k8sda.lnf.infn.it"
          kafka:
            replicaCount: 3
            targetRevision: '30.1.6'  # Using older stable version with available images
            
            # IMPORTANT: Override image to use your own registry mirror
            # Bitnami removed public docker.io/bitnami on Aug 28, 2025
            image:
              registry: your-registry.example.com  # Replace with your registry!
              repository: bitnami/kafka
              tag: 3.8.0-debian-12-r5  # Or any available tag in your registry
            
            externalAccess:
              enabled: true
              controller:
                service:
                  type: LoadBalancer
                  loadBalancerIPs:
                    - 10.10.6.250
                    - 10.10.6.251
                    - 10.10.6.252
                  ports:
                    external: 9092
            
            # Required for external access with LoadBalancer
            listeners:
              client:
                protocol: PLAINTEXT
              controller:
                protocol: PLAINTEXT
              interbroker:
                protocol: PLAINTEXT
              external:
                protocol: PLAINTEXT
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Prune=true
