apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epik8-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/epik8-backend.git'
    path: .
    targetRevision: bitnamilegacy
    helm:
      values: |
          namespace: backend
          domain: "apps.okd-datest.lnf.infn.it"
          openshift: true
          size: 50Gi
          kafka:
            replicaCount: 3
            externalAccess:
              enabled: true
      
              service:
                type: LoadBalancer
                loadBalancerIPs:
                    - 192.168.36.251
                    - 192.168.36.252
                    - 192.168.36.253
                ports:
                  external: 9092
      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - Prune=true
