apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epik8-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/infn-epics/epik8s-backend.git'
    path: .
    targetRevision: bitnamilegacy
    helm:
      values: |
          namespace: backend
          domain: "apps.okd-datest.lnf.infn.it"
          openshift: true
          size: 5Gi
          mongo:
            enabled: true
            replicaCount: 1
            storageClassName: "archiver-lts"
            auth:
              enabled: false
            resources:
              limits:
                cpu: 2
                memory: 2Gi
              requests:
                cpu: 1
                memory: 1Gi
          kafka:
            replicaCount: 1
            externalAccess:
              enabled: true
      
              service:
                type: LoadBalancer
                loadBalancerIPs:
                    - 192.168.36.251
                   
                ports:
                  external: 9092
      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: false  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: false
    syncOptions:
      - CreateNamespace=true 
      - Prune=true
