replicaCount: 3

# Disable the init containers auto-discovery (Bitnami chart validation expects this)
defaultInitContainers:
  autoDiscovery:
    enabled: false

externalAccess:
  enabled: true
  controller:
    service:
      type: LoadBalancer
      loadBalancerIPs:
        - 10.10.6.250
        - 10.10.6.251
        - 10.10.6.252
      ports:
        external: 9092
