apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: argocd
spec:
  project: default
  
  source:
    chart: eck-operator
    repoURL: https://helm.elastic.co
    targetRevision: {{ .Values.elasticsearch.targetRevision | default "3.2.0" }}
    helm:
      releaseName: eck-operator
      values: |
        # Manage all namespaces
        managedNamespaces: []
        
        # Create CRDs
        installCRDs: true
        
        # Resource limits
        {{- if .Values.elasticsearch.resources }}
        resources:
        {{ toYaml .Values.elasticsearch.resources | indent 12 }}
        {{- end }}
        # Pod configuration
        podAnnotations: {}
        podLabels: {}
        
        # Webhook configuration
        webhook:
          enabled: true
          port: 9443
        
        # Log configuration
        config:
          logVerbosity: "0"
          metricsPort: "0"
          maxConcurrentReconciles: "3"
          
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m