apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-search
  namespace: argocd
  labels:
    rootapp: {{ .Chart.Name }}
    rootappver: {{ .Chart.Version }}
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: "8.5.1"

    path: "elastic/elasticsearch"
    targetRevision: HEAD
    helm:
      parameters:
        - name: secret.password
          value: "notchaos"
        
            
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
