apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Using official Elastic Helm charts
    # See: https://github.com/elastic/helm-charts
    repoURL: 'https://helm.elastic.co'
    targetRevision: {{ .Values.elasticsearch.targetRevision | quote }}
    chart: elasticsearch
    helm:
      values: |
        # Elasticsearch cluster configuration
        clusterName: "elastic"
        
        # Single-node deployment
        replicas: {{ .Values.elasticsearch.replicaCount }}
        minimumMasterNodes: 1
        
        # Disable security features for simplicity
        esConfig:
          elasticsearch.yml: |
            xpack.security.enabled: false
            xpack.security.transport.ssl.enabled: false
            xpack.security.http.ssl.enabled: false
        
        # Resource limits
        {{- if .Values.elasticsearch.resources }}
        resources:
{{ toYaml .Values.elasticsearch.resources | indent 10 }}
        {{- end }}
        
        # Persistence
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: {{ .Values.size | quote }}
        
        # Service
        service:
          type: ClusterIP
          port: 9200
        
        # Ingress for Elasticsearch
        ingress:
          enabled: true
          {{- if .Values.ingressClassName }}
          className: {{ .Values.ingressClassName | quote }}
          {{- end }}
          hosts:
            - host: elasticsearch.{{ .Values.domain }}
              paths:
                - path: /
        
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
---
# Kibana Application
{{- if .Values.elasticsearch.kibanaEnabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Using official Elastic Helm charts
    repoURL: 'https://helm.elastic.co'
    targetRevision: {{ .Values.elasticsearch.kibanaTargetRevision | default .Values.elasticsearch.targetRevision | quote }}
    chart: kibana
    helm:
      values: |
        # Kibana configuration
        elasticsearchHosts: "http://elasticsearch-master.{{ .Values.namespace }}.svc.cluster.local:9200"
        
        # Resource limits
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        
        # Service
        service:
          type: ClusterIP
          port: 5601
        
        # Ingress for Kibana
        ingress:
          enabled: true
          {{- if .Values.ingressClassName }}
          className: {{ .Values.ingressClassName | quote }}
          {{- end }}
          hosts:
            - host: kibana.{{ .Values.domain }}
              paths:
                - path: /
  
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
  

