apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-search
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      values: |
        secret:
          password: "notchaos"
        securityContext:
          runAsUser: null

        podSecurityContext:
          fsGroup: null
          runAsUser: null

        sysctlInitContainer:
          enabled: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

