apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'  # Bitnami Helm repo
    targetRevision: {{.Values.kafka.targetRevision}}
    chart: kafka
    helm:
      values: |
        architecture: standalone
        zookeeper:
          enabled: true
          auth:
            enabled: false
          replicaCount: 1
        
        serviceAccount:
          create: false
          name: "default"
        rbac:
          create: true
        
        
        service:
          clusterIP: None
{{- if .Values.kafka.resources }}
        resources:
{{ toYaml .Values.kafka.resources | indent 12 }}
{{- end }}
        auth:
          enable: false
          clientProtocol: plaintext
          interBrokerProtocol: plaintext
      {{- if .Values.kafka.externalAccess }}
        externalAccess:
{{ toYaml .Values.kafka.externalAccess | indent 12 }}
      {{- end }}
        controller:
          replicaCount: 0 # {{.Values.kafka.replicaCount}}
          
        # serviceAccount:
        #     name: "default"
        #     create: false
        
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  

