apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'  # Bitnami Helm repo
    targetRevision: {{.Values.kafka.targetRevision}}
    chart: kafka
    helm:
      values: |
        architecture: standalone
        zookeeper:
          enabled: true
        kraft:
          enabled: false

        listeners:
          client:
            protocol: PLAINTEXT
  
          controller:
            protocol: PLAINTEXT

          interbroker:
            protocol: PLAINTEXT
  
          external:
            protocol: PLAINTEXT
        
          # enable: false
          # interbroker:
          #   user: ""
          #   password: ""
          # controller:
          #   user: ""
          #   password: ""
        
        zookeeper:
          auth:
            enabled: false
        broker:
          zookeeperMigrationMode: true
        auth:
          enable: false
          clientProtocol: PLAINTEXT
          interBrokerProtocol: PLAINTEXT
      {{- if .Values.kafka.externalAccess }}
        externalAccess:
{{ toYaml .Values.kafka.externalAccess | indent 12 }}
      {{- end }}
        controller:
          replicaCount: 0 # {{.Values.kafka.replicaCount}}
          {{- if .Values.kafka.resources }}
          resources:
{{ toYaml .Values.kafka.resources | indent 12 }}
          {{- end }}
        # serviceAccount:
        #     name: "default"
        #     create: false
        
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  

