apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'
    targetRevision: {{ .Values.kafka.targetRevision | quote }}
    chart: kafka
    helm:
      values: |
        replicaCount: {{ .Values.kafka.replicaCount }}
        architecture: replicatedKRaft
        
        serviceAccount:
          create: false
          name: "default"
        
        rbac:
          create: true
        
        service:
          clusterIP: None
        {{- if .Values.kafka.resources }}
        
        resources:
{{ toYaml .Values.kafka.resources | indent 10 }}
        {{- end }}
        
        auth:
          enable: false
          clientProtocol: {{ .Values.kafka.auth.clientProtocol | default "plaintext" }}
          interBrokerProtocol: {{ .Values.kafka.auth.interBrokerProtocol | default "plaintext" }}
        {{- if .Values.kafka.externalAccess }}
        
        externalAccess:
{{ toYaml .Values.kafka.externalAccess | indent 10 }}
        {{- end }}
        
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  

