---
# Strimzi Kafka Operator Installation
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://strimzi.io/charts/'
    targetRevision: {{ .Values.kafka.strimzi.operatorVersion | default "0.48.0" | quote }}
    chart: strimzi-kafka-operator
    helm:
      values: |
        # Leave watchNamespaces empty - it defaults to .Release.Namespace
        watchNamespaces: []
{{- if .Values.kafka.strimzi.operatorResources }}
        resources:
{{ toYaml .Values.kafka.strimzi.operatorResources | indent 10 }}
{{- end }}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
# Kafka Cluster Application
{{- if .Values.kafka.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Using this chart's kafka manifests
    repoURL: {{ .Values.kafka.strimzi.repoURL | default "https://github.com/infn-epics/epik8s-backend.git" | quote }}
    targetRevision: {{ .Values.kafka.strimzi.targetRevision | default "HEAD" | quote }}
    path: manifests/kafka
  
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
