apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName | default "kafka-cluster" }}
spec:
  replicas: {{ .Values.kafka.replicaCount   | default 3 }}
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared

---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.kafka.clusterName | default "kafka-cluster" }}
spec:
  kafka:
    version: {{ .Values.kafka.version | default "4.1.0" }}
    metadataVersion: {{ .Values.kafka.metadataVersion | default "4.1-IV1" }}
    listeners:
      - name: plain
        port: {{ .Values.kafka.listeners.plain.port | default 9092 }}
        type: internal
        tls: false
    {{- if or .Values.kafka.externalAccess.bootstrap .Values.kafka.externalAccess.brokers }}
      - name: external
        port: {{ .Values.kafka.externalAccess.port | default 9092 }}
        type: loadbalancer
        tls: false
        configuration:
          {{- if .Values.kafka.externalAccess.bootstrap }}
          bootstrap:
{{ toYaml .Values.kafka.externalAccess.bootstrap | indent 12 }}
          {{- end }}
          {{- if .Values.kafka.externalAccess.brokers }}
          brokers:
{{ toYaml .Values.kafka.externalAccess.brokers | indent 12 }}
          {{- end }}
    {{- end }}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}