apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'  # Bitnami Helm repo
    targetRevision: '14.12.3' 
    chart: mongodb
    helm:
      values: |
        architecture: standalone
        replicaCount: 1
        serviceAccount:
            name: "default"
            create: false
        auth:
          enabled: false
          
          
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      syncTimeout: 10m
  resource:
  customizations:
    timeout:
      seconds: 600

