apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'  # Bitnami Helm repo
    targetRevision: '14.12.3'  # Specify the version of MySQL you wish to deploy
    chart: mongodb
    helm:
      values: |
        architecture: standalone
        replicaCount: 1
        auth:
          enabled: false
        securityContext:
          privileged: true
          runAsUser: 0 
          runAsGroup: 0
          fsGroup: 0
        containerSecurityContext:
          allowPrivilegeEscalation: true
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


