{{- if .Values.mongo.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongo.storageClassName | default "archiver-lts" }}
  resources:
    requests:
      storage: {{ .Values.mongo.storage.size | default "10Gi" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  serviceName: mongodb
  replicas: {{ .Values.mongo.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        {{- if .Values.mongo.resources }}
        resources:
{{ toYaml .Values.mongo.resources | indent 10 }}
        {{- end }}
        {{- if .Values.mongo.auth.enabled }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongo.auth.rootUser | default "root" | quote }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongo.auth.rootPassword | default "changeme" | quote }}
        {{- if .Values.mongo.auth.database }}
        - name: MONGO_INITDB_DATABASE
          value: {{ .Values.mongo.auth.database | quote }}
        {{- end }}
        {{- end }}
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data
{{- end }}
  

