apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'  # Bitnami Helm repo
    targetRevision: {{.Values.mongo.targetRevision}}
    chart: mongodb
    helm:
      values: |
        global:
          storageClass: {{ .Values.mongo.storageClassName | default "archiver-lts" }}
          
        image:
          repository: {{ .Values.mongo.image.repository }}
          tag: {{ .Values.mongo.image.tag }}
        volumePermissions:
          image:
            repository: bitnamilegacy/os-shell
            tag: {{ .Values.mongo.volumePermissions.image.tag | default "11-debian-11-r99" }}
          enabled: true
        metrics:
          image:
            repository: bitnamilegacy/mongodb-exporter
            tag: "0.39.0-debian-11-r0"

        serviceAccount:
          name: "default"
        persistence:
          enabled: true
          size: {{ .Values.mongo.size | default "10Gi" }}
          storageClass: {{ .Values.mongo.storageClassName | default "archiver-lts" }}
          
        auth:
          enabled: false
        
        metrics:
          image:
            repository: {{ .Values.mongo.metrics.image.repository }}
            tag: {{ .Values.mongo.metrics.image.tag }}
        architecture: standalone
        replicaCount: {{.Values.mongo.replicaCount}}
        {{- if .Values.mongo.resources }}
        resources:
{{ toYaml .Values.mongo.resources | indent 12 }}
        {{- end }}
        
        
          
          
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  

