{{- if .Values.mongo.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Using this chart's mongodb manifests
    repoURL: {{ .Values.mongo.repoURL | default "https://github.com/infn-epics/epik8s-backend.git" | quote }}
    targetRevision: {{ .Values.mongo.targetRevision | default "HEAD" | quote }}
    path: manifests/mongodb
  
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
  

