apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'  # Bitnami Helm repo
    targetRevision: {{.Values.mongo.targetRevision}}
    chart: mongodb
    helm:
      values: |
        image:
          repository: {{ .Values.mongo.image.repository }}
          tag: {{ .Values.mongo.image.tag }}
        metrics:
          image:
            repository: {{ .Values.mongo.metrics.image.repository }}
            tag: {{ .Values.mongo.metrics.image.tag }}
        architecture: standalone
        replicaCount: {{.Values.mongo.replicaCount}}
        {{- if .Values.mongo.resources }}
        resources:
{{ toYaml .Values.mongo.resources | indent 12 }}
        {{- end }}
        serviceAccount:
            name: "default"
            create: false
        auth:
          enabled: false
        
          
          
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  

